nodeLinker: node-modules

packageExtensions:
  jest-cli@*:
    dependencies:
      "@jest/console": "*"
      "@jest/reporters": "*"
  jest-config@*:
    dependencies:
      jest-runtime: "*"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
